// refervo.com/share/biz?d=BASE64URL_PAYLOAD
//
// Public landing page for "My Biz" share links generated by the mobile app.
// The URL itself carries the entire card payload (name, phone, optional email
// and note) — there's no DB lookup, no analytics, no cookies. Just a
// stateless decode-and-render.
//
// The matching encoder/decoder lives in mobile (refervo-app) at
// src/utils/myBizShare.ts and is mirrored here in _shared.js (kept in sync
// by hand).
//
// Recipients on a device with the ReferVo app can tap "Add to My ReferVo" to
// deep-link straight into the import flow (handled in Phase 3c). Recipients
// without the app land on /get which routes them to the right store.

import { decodeMyBizShareUrl } from './_shared.js';

const DOWNLOAD_URL = 'https://refervo.com/get';

// ───────────────────────────────────────────────────────────────────
// Route entry
// ───────────────────────────────────────────────────────────────────
export async function onRequest(context) {
  const { request } = context;
  const url = new URL(request.url);
  const d = url.searchParams.get('d');

  const card = decodeMyBizShareUrl(d);

  if (!card) {
    return htmlResponse(renderInvalidShare(), 400);
  }

  return htmlResponse(renderShare({ card, rawD: d }), 200);
}

// ───────────────────────────────────────────────────────────────────
// Helpers
// ───────────────────────────────────────────────────────────────────

function escapeHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatPhone(phone) {
  const digits = String(phone || '').replace(/\D/g, '');
  if (digits.length === 10) {
    return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
  }
  return String(phone || '');
}

// Mirrors functions/r/[code].js exactly so the two pages share visual chrome.
function baseStyles() {
  return `
    :root {
      --orange: #f97316;
      --orange-light: #fb923c;
      --orange-dark: #ea580c;
      --black: #1a1a1a;
      --white: #ffffff;
      --gray-text: #6b7280;
      --gray-strong: #374151;
      --gray-light: #f3f4f6;
      --gray-border: #e5e7eb;
      --red: #dc2626;
      --red-light: #fef2f2;
      --green: #16a34a;
      --green-light: #f0fdf4;
      --font-display: 'Plus Jakarta Sans', sans-serif;
      --font-body: 'DM Sans', sans-serif;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: var(--font-body);
      background: linear-gradient(180deg, var(--gray-light) 0%, var(--white) 100%);
      min-height: 100vh;
      padding: 2rem 1rem;
      color: var(--black);
      -webkit-font-smoothing: antialiased;
    }
    .container { max-width: 460px; margin: 0 auto; }
    .logo { text-align: center; font-family: var(--font-display); font-size: 1.75rem; font-weight: 800; letter-spacing: -0.02em; margin-bottom: 1.5rem; }
    .logo-refer { color: var(--orange); }
    .logo-vo    { color: var(--black); }
    .card { background: var(--white); border-radius: 20px; padding: 1.75rem 1.5rem; box-shadow: 0 12px 40px rgba(0, 0, 0, 0.08); }
    h1 { font-family: var(--font-display); font-size: 1.5rem; font-weight: 800; line-height: 1.25; margin-bottom: 0.5rem; }
    .subtitle { color: var(--gray-text); font-size: 0.95rem; margin-bottom: 1.5rem; line-height: 1.5; }
    .btn { display: flex; align-items: center; justify-content: center; gap: 0.5rem; width: 100%; font-family: var(--font-display); font-weight: 700; font-size: 1rem; padding: 0.95rem 1.25rem; border-radius: 12px; border: none; cursor: pointer; margin-top: 1.5rem; transition: transform 0.1s ease, box-shadow 0.15s ease; }
    .btn-primary { background: var(--black); color: var(--white); }
    .btn-primary:hover { transform: translateY(-1px); box-shadow: 0 8px 20px rgba(0, 0, 0, 0.18); }
    .btn-primary:active { transform: translateY(0); }
    .footer { text-align: center; margin-top: 1.5rem; font-size: 0.8rem; color: var(--gray-text); }
    .footer a { color: var(--orange); text-decoration: none; }
    .footer a:hover { text-decoration: underline; }

    /* /share/biz-specific blocks */
    .biz-preview {
      background: var(--gray-light);
      border-radius: 14px;
      padding: 1.25rem 1.25rem;
      margin-bottom: 1.25rem;
    }
    .biz-name {
      font-family: var(--font-display);
      font-size: 1.4rem;
      font-weight: 800;
      color: var(--black);
      line-height: 1.25;
      margin-bottom: 0.5rem;
      word-break: break-word;
    }
    .biz-meta-row {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      color: var(--gray-strong);
      font-size: 0.95rem;
      margin-top: 0.4rem;
    }
    .biz-meta-row svg { flex-shrink: 0; color: var(--gray-text); }
    .biz-meta-row a {
      color: var(--gray-strong);
      text-decoration: none;
      word-break: break-all;
    }
    .biz-meta-row a:hover { color: var(--orange-dark); }
    .biz-email { font-size: 0.85rem; color: var(--gray-text); }
    .biz-note {
      margin-top: 1rem;
      padding: 0.85rem 1rem;
      background: var(--white);
      border-left: 4px solid var(--orange);
      border-radius: 8px;
      color: var(--gray-strong);
      font-size: 0.9rem;
      font-style: italic;
      line-height: 1.5;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .cta-primary {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      width: 100%;
      background: var(--orange);
      color: var(--white);
      font-family: var(--font-display);
      font-weight: 700;
      font-size: 1rem;
      padding: 1rem 1.25rem;
      border-radius: 12px;
      text-decoration: none;
      box-sizing: border-box;
      transition: background 0.15s ease, transform 0.1s ease;
    }
    .cta-primary:hover { background: var(--orange-dark); transform: translateY(-1px); }
    .cta-primary:active { transform: translateY(0); }
    .cta-secondary {
      display: block;
      text-align: center;
      margin-top: 0.85rem;
      font-size: 0.9rem;
      color: var(--gray-text);
      text-decoration: none;
    }
    .cta-secondary strong { color: var(--orange-dark); font-weight: 700; }
    .cta-secondary:hover strong { text-decoration: underline; }
  `;
}

function headHtml(title, ogMeta = '') {
  return `
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <meta name="robots" content="noindex">
    <title>${escapeHtml(title)}</title>
    ${ogMeta}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=DM+Sans:wght@400;500;600&display=swap" rel="stylesheet">
    <style>${baseStyles()}</style>
  `;
}

// ───────────────────────────────────────────────────────────────────
// Templates
// ───────────────────────────────────────────────────────────────────

function renderShare({ card, rawD }) {
  const safeName  = escapeHtml(card.name);
  const safePhone = escapeHtml(formatPhone(card.phone));
  // tel: URIs use the raw digits, not the display-formatted version
  const telDigits = String(card.phone || '').replace(/\D/g, '');
  const safeTel   = escapeHtml(telDigits);
  const safeEmail = card.email ? escapeHtml(card.email) : null;
  const safeNote  = card.note ? escapeHtml(card.note) : null;

  // Preserve the d param exactly as received in the deep link so the app's
  // import handler decodes the same payload the landing page just rendered.
  const deepLink  = `refervo://share/biz?d=${encodeURIComponent(rawD)}`;

  const ogMeta = `
    <meta property="og:title" content="${safeName} on ReferVo">
    <meta property="og:description" content="Someone shared this business with you. Tap to add it to your network.">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary">
  `;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${headHtml(`${card.name} on ReferVo`, ogMeta)}
</head>
<body>
  <div class="container">
    <div class="logo">
      <span class="logo-refer">Refer</span><span class="logo-vo">Vo</span>
    </div>

    <div class="card">
      <h1>Someone shared this business with you on ReferVo</h1>
      <p class="subtitle">Add them to your network so you can refer them and track who you trust.</p>

      <div class="biz-preview">
        <div class="biz-name">${safeName}</div>

        <div class="biz-meta-row">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/>
          </svg>
          <a href="tel:${safeTel}">${safePhone}</a>
        </div>

        ${safeEmail ? `
        <div class="biz-meta-row biz-email">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
            <polyline points="22,6 12,13 2,6"/>
          </svg>
          <a href="mailto:${safeEmail}">${safeEmail}</a>
        </div>
        ` : ''}

        ${safeNote ? `<div class="biz-note">${safeNote}</div>` : ''}
      </div>

      <a href="${deepLink}" class="cta-primary">
        Add to My ReferVo
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <line x1="5" y1="12" x2="19" y2="12"/>
          <polyline points="12 5 19 12 12 19"/>
        </svg>
      </a>

      <a href="${DOWNLOAD_URL}" class="cta-secondary">
        Don\u2019t have ReferVo? <strong>Get it \u2192</strong>
      </a>
    </div>

    <div class="footer">
      Powered by <a href="https://refervo.com">ReferVo</a>
    </div>
  </div>
</body>
</html>`;
}

function renderInvalidShare() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${headHtml('This share link doesn\u2019t seem complete')}
</head>
<body>
  <div class="container">
    <div class="logo">
      <span class="logo-refer">Refer</span><span class="logo-vo">Vo</span>
    </div>
    <div class="card" style="text-align:center;">
      <h1>This share link doesn\u2019t seem complete</h1>
      <p class="subtitle">Ask the sender to share again. Links sometimes get truncated when copied across apps.</p>
      <a href="https://refervo.com" class="btn btn-primary" style="text-decoration:none;">Go to refervo.com</a>
    </div>
  </div>
</body>
</html>`;
}

function htmlResponse(html, status = 200) {
  return new Response(html, {
    status,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'no-referrer-when-downgrade',
    },
  });
}
